import 'package:flutter/material.dart';

class _HandmadeIcons extends IconData {
  const _HandmadeIcons(int codePoint)
      : super(codePoint,
            fontFamily: 'mbi_handmade', fontPackage: 'icon_forest');
}

class MbiHandmadeIcons {
  static const IconData zoom_out = _HandmadeIcons(0xe900);
  static const IconData zoom_in = _HandmadeIcons(0xe901);
  static const IconData wrench = _HandmadeIcons(0xe902);
  static const IconData user_1 = _HandmadeIcons(0xe903);
  static const IconData user = _HandmadeIcons(0xe904);
  static const IconData upload_3 = _HandmadeIcons(0xe905);
  static const IconData upload_2 = _HandmadeIcons(0xe906);
  static const IconData upload_1 = _HandmadeIcons(0xe907);
  static const IconData upload = _HandmadeIcons(0xe908);
  static const IconData up_arrow_2 = _HandmadeIcons(0xe909);
  static const IconData up_arrow_1 = _HandmadeIcons(0xe90a);
  static const IconData up_arrow = _HandmadeIcons(0xe90b);
  static const IconData transfer_2 = _HandmadeIcons(0xe90c);
  static const IconData transfer_1 = _HandmadeIcons(0xe90d);
  static const IconData transfer = _HandmadeIcons(0xe90e);
  static const IconData telephone_1 = _HandmadeIcons(0xe90f);
  static const IconData telephone = _HandmadeIcons(0xe910);
  static const IconData target = _HandmadeIcons(0xe911);
  static const IconData sticker = _HandmadeIcons(0xe912);
  static const IconData speech_bubble_3 = _HandmadeIcons(0xe913);
  static const IconData speech_bubble_2 = _HandmadeIcons(0xe914);
  static const IconData speech_bubble_1 = _HandmadeIcons(0xe915);
  static const IconData speech_bubble = _HandmadeIcons(0xe916);
  static const IconData speaker = _HandmadeIcons(0xe917);
  static const IconData sort = _HandmadeIcons(0xe918);
  static const IconData shuffle_1 = _HandmadeIcons(0xe919);
  static const IconData shuffle = _HandmadeIcons(0xe91a);
  static const IconData shield = _HandmadeIcons(0xe91b);
  static const IconData share = _HandmadeIcons(0xe91c);
  static const IconData settings = _HandmadeIcons(0xe91d);
  static const IconData send = _HandmadeIcons(0xe91e);
  static const IconData search = _HandmadeIcons(0xe91f);
  static const IconData right_arrow_1 = _HandmadeIcons(0xe920);
  static const IconData right_arrow = _HandmadeIcons(0xe921);
  static const IconData repeat_3 = _HandmadeIcons(0xe922);
  static const IconData repeat_2 = _HandmadeIcons(0xe923);
  static const IconData repeat_1 = _HandmadeIcons(0xe924);
  static const IconData repeat = _HandmadeIcons(0xe925);
  static const IconData reload = _HandmadeIcons(0xe926);
  static const IconData refresh = _HandmadeIcons(0xe927);
  static const IconData push_pin = _HandmadeIcons(0xe928);
  static const IconData previous_2 = _HandmadeIcons(0xe929);
  static const IconData previous_1 = _HandmadeIcons(0xe92a);
  static const IconData previous = _HandmadeIcons(0xe92b);
  static const IconData paper_clip = _HandmadeIcons(0xe92c);
  static const IconData padlock_1 = _HandmadeIcons(0xe92d);
  static const IconData padlock = _HandmadeIcons(0xe92e);
  static const IconData next_3 = _HandmadeIcons(0xe92f);
  static const IconData next_2 = _HandmadeIcons(0xe930);
  static const IconData next_1 = _HandmadeIcons(0xe931);
  static const IconData next = _HandmadeIcons(0xe932);
  static const IconData muted = _HandmadeIcons(0xe933);
  static const IconData musical_note = _HandmadeIcons(0xe934);
  static const IconData move = _HandmadeIcons(0xe935);
  static const IconData mail = _HandmadeIcons(0xe936);
  static const IconData login_1 = _HandmadeIcons(0xe937);
  static const IconData login = _HandmadeIcons(0xe938);
  static const IconData list = _HandmadeIcons(0xe939);
  static const IconData link = _HandmadeIcons(0xe93a);
  static const IconData levels_1 = _HandmadeIcons(0xe93b);
  static const IconData levels = _HandmadeIcons(0xe93c);
  static const IconData left_arrow_2 = _HandmadeIcons(0xe93d);
  static const IconData left_arrow_1 = _HandmadeIcons(0xe93e);
  static const IconData left_arrow = _HandmadeIcons(0xe93f);
  static const IconData inbox = _HandmadeIcons(0xe940);
  static const IconData home = _HandmadeIcons(0xe941);
  static const IconData headphones = _HandmadeIcons(0xe942);
  static const IconData head = _HandmadeIcons(0xe943);
  static const IconData forbidden = _HandmadeIcons(0xe944);
  static const IconData folder = _HandmadeIcons(0xe945);
  static const IconData export = _HandmadeIcons(0xe946);
  static const IconData expand = _HandmadeIcons(0xe947);
  static const IconData edit = _HandmadeIcons(0xe948);
  static const IconData download_4 = _HandmadeIcons(0xe949);
  static const IconData download_3 = _HandmadeIcons(0xe94a);
  static const IconData download_2 = _HandmadeIcons(0xe94b);
  static const IconData download_1 = _HandmadeIcons(0xe94c);
  static const IconData download = _HandmadeIcons(0xe94d);
  static const IconData down_arrow_1 = _HandmadeIcons(0xe94e);
  static const IconData down_arrow = _HandmadeIcons(0xe94f);
  static const IconData cursor_2 = _HandmadeIcons(0xe950);
  static const IconData cursor_1 = _HandmadeIcons(0xe951);
  static const IconData cursor = _HandmadeIcons(0xe952);
  static const IconData compress = _HandmadeIcons(0xe953);
  static const IconData coins = _HandmadeIcons(0xe954);
  static const IconData coin = _HandmadeIcons(0xe955);
  static const IconData close_1 = _HandmadeIcons(0xe956);
  static const IconData close = _HandmadeIcons(0xe957);
  static const IconData click = _HandmadeIcons(0xe958);
  static const IconData checked_2 = _HandmadeIcons(0xe959);
  static const IconData checked_1 = _HandmadeIcons(0xe95a);
  static const IconData checked = _HandmadeIcons(0xe95b);
  static const IconData broken_link = _HandmadeIcons(0xe95c);
  static const IconData bookmark = _HandmadeIcons(0xe95d);
  static const IconData basket = _HandmadeIcons(0xe95e);
  static const IconData add = _HandmadeIcons(0xe95f);
}
